# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_configuration.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("userconfiguration.proto", :syntax => :proto2) do
    add_message "FYBER.userconfiguration.Creative" do
      required :id, :string, 1
      required :price, :float, 2
    end
    add_message "FYBER.userconfiguration.CreativeSeq" do
      repeated :creative, :message, 1, "FYBER.userconfiguration.Creative"
    end
    add_message "FYBER.userconfiguration.Placement" do
      required :id, :string, 1
      repeated :creative, :message, 2, "FYBER.userconfiguration.Creative"
    end
    add_message "FYBER.userconfiguration.PlacementSeq" do
      repeated :placement, :message, 1, "FYBER.userconfiguration.Placement"
    end
  end
end

module FYBER
  module Userconfiguration
    Creative = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FYBER.userconfiguration.Creative").msgclass
    CreativeSeq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FYBER.userconfiguration.CreativeSeq").msgclass
    Placement = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FYBER.userconfiguration.Placement").msgclass
    PlacementSeq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FYBER.userconfiguration.PlacementSeq").msgclass
  end
end
